---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
#  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: centos_php54
    run_list:
      - recipe[as-symfony2::create]
      - recipe[as-symfony2::install]
    attributes:
      php:
        version: '5.4'
        date.timezone: 'Asia/Tokyo'
        xdebug:
          remote_enable: true
      symfony2:
        path: '/var/app'
        acl: false
  - name: centos_php55
    run_list:
      - recipe[as-symfony2::create]
#      - recipe[as-symfony2::install]
    attributes:
      php:
        version: '5.5'
        date.timezone: 'Asia/Tokyo'
        xdebug:
          remote_enable: true
      symfony2:
        path: '/var/app'
        acl: false
  - name: centos_php56
    run_list:
      - recipe[as-symfony2::create]
#      - recipe[as-symfony2::install]
    attributes:
      php:
        version: '5.6'
        date.timezone: 'Asia/Tokyo'
        xdebug:
          remote_enable: true
      symfony2:
        path: '/var/app'
        acl: false
